'use client';
import {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import AppShell from '@/app/components/AppShell';
import CandidateWorkspace from '@/app/components/CandidateWorkspace';
import JobWorkspace from '@/app/components/JobWorkspace';
import CrmWorkspace from '@/app/components/CrmWorkspace';
import EnterpriseTable from '@/app/components/EnterpriseTable';
export default function QA(){const params=useSearchParams();const [view,setView]=useState(params.get('view')||'candidates');return <AppShell user={{agency_name:'QA Staffing LLC',display_name:'QA Reviewer',email:'qa@example.invalid',role:'OWNER'}} globalSettings={{country_name:'United States',timezone_id:'America/New_York',language_code:'en'}} active={view}><div className="page-heading"><div><span className="page-kicker">LOCAL QA FIXTURES</span><h1>{view==='candidates'?'Candidate workspace':view==='jobs'?'Client requirements':'Client accounts'}</h1><p>Local component testing only. These records are illustrative.</p></div></div><div className="fast-action-strip">{['candidates','jobs','clients','table'].map(v=><button key={v} onClick={()=>setView(v)}>{v}</button>)}</div>{view==='candidates'?<CandidateWorkspace context={{rows:[{id:'qa1',full_name:'Jordan Davis',email:'jordan@example.invalid',current_title:'Senior Software Engineer',current_company:'Example Systems',city:'Austin',country_code:'US',availability_status:'AVAILABLE_NOW',salary_expected:120000,salary_currency:'USD',updated_at:'2026-09-30'}],total:1}} countries={[{country_code:'US',country_name:'United States'}]} timezones={[{country_code:'US',timezone_id:'America/New_York',display_name:'Eastern Time'}]}/>:view==='jobs'?<JobWorkspace context={{rows:[{id:'qa1',title:'Senior Software Engineer',account_name:'Example Client',status:'OPEN',priority:'HIGH',location:'Austin, TX',openings:2}],total:1}}/>:view==='clients'?<CrmWorkspace module="CLIENT" context={{rows:[{id:'qa1',name:'Example Client',status:'ACTIVE',health_status:'HEALTHY',open_jobs:2,owner_name:'QA Reviewer'}],total:1}} reference={{}}/>:<EnterpriseTable rows={Array.from({length:30},(_,i)=>({id:i,name:'Candidate '+i}))} columns={[{key:'name',label:'Candidate'}]} pageSize={25} rowActions={[{label:'Open',onClick:()=>{}}]}/>}</AppShell>}
