import Link from 'next/link';
import { ArrowRight, BriefcaseBusiness, Building2, CalendarDays, Check, CheckCheck, FileCheck2, GitBranch, LockKeyhole, ShieldCheck, Users } from 'lucide-react';
import Brand from '@/app/components/Brand';

const features = [
  [BriefcaseBusiness, 'Requirements to ready submissions', 'Capture client requirements, review hiring briefs, assign recruiters and prepare candidate submissions in a connected workflow.'],
  [Users, 'One complete candidate record', 'Keep profiles, resumes, skills, availability, work authorization and screening evidence together. Review parsed information before applying it.'],
  [Building2, 'Clients and partners, connected', 'Manage accounts, contacts, opportunities and vendors. Share submissions through secure client and vendor portals.'],
  [GitBranch, 'A pipeline your team can follow', 'Move applications through configured stages with screening, interview and offer requirements checked along the way.'],
  [CalendarDays, 'Interviews without the timezone guesswork', 'Schedule across US timezones and international teams, collect scorecards and keep candidate context close at hand.'],
  [FileCheck2, 'From offer to placement', 'Track approvals, offer decisions, start dates and placement fees alongside the candidate’s recruitment history.']
];

export default function Home() {
  return <main className="marketing">
    <div className="shell"><nav className="marketing-nav" aria-label="Main navigation"><Brand/><div className="marketing-links"><a href="#product">Platform</a><a href="#workflow">How it works</a><a href="#security">Workspace security</a></div><div className="marketing-actions"><Link className="btn ghost" href="/login">Sign in</Link><Link className="btn primary" href="/signup">Create workspace <ArrowRight size={15}/></Link></div></nav>
      <section className="marketing-hero"><div><div className="marketing-label"><i/>Recruitment operations, connected</div><h1>Every requirement.<br/>Every candidate.<br/><span>One clear workflow.</span></h1><p>Give your staffing team a shared place to manage client requirements, recruiter activity, candidate submissions and placements — from the first conversation to the first day.</p><div className="hero-actions"><Link href="/signup" className="btn primary">Set up your workspace <ArrowRight size={16}/></Link><a href="#product" className="btn ghost">Explore the platform</a></div><div className="marketing-note"><ShieldCheck size={15}/>For US staffing companies and distributed recruiting teams</div></div>
        <div className="preview-workspace" aria-label="Illustrative recruitment workspace"><div className="preview-header"><b>Recruitment workspace</b><small>TEAM OVERVIEW</small></div><div className="preview-content"><small>YOUR TEAM, IN SYNC</small><h3>A clear path to the next hire</h3><div className="preview-flow"><div><small>Requirements</small><b>Review</b></div><div><small>Candidates</small><b>Screen</b></div><div><small>Submissions</small><b>Approve</b></div></div><div className="preview-requirement"><div><b>Senior Software Engineer</b><span className="status good">Open</span></div><small>Client requirement · Austin, TX · Hybrid</small><div className="preview-tags"><span>Java</span><span>AWS</span><span>Contract</span></div><div className="preview-person"><span className="preview-avatar">JD</span><div><b>Jordan Davis</b><small>Screening completed · Ready for review</small></div><CheckCheck size={17} color="#0f766e"/></div></div></div><div className="preview-caption">Illustrative workflow. Your workspace shows your team’s saved records.</div></div>
      </section></div>
    <div className="marketing-strip"><div className="shell">{[[BriefcaseBusiness,'Client requirements'],[Users,'Candidate management'],[FileCheck2,'Submission reviews'],[CalendarDays,'Interviews & offers']].map(([Icon,label])=><span key={label}><Icon size={17}/>{label}</span>)}</div></div>
    <section className="marketing-section shell" id="product"><div className="marketing-label">A shared operating system for your agency</div><h2>Less switching. More recruiting.</h2><p className="section-intro">Connect the work recruiters, account managers and agency leaders do every day. Keep the details visible and the next action easy to find.</p><div className="feature-grid">{features.map(([Icon,title,description])=><article className="feature-card" key={title}><div className="feature-icon"><Icon size={19}/></div><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="marketing-section workflow-section" id="workflow"><div className="shell"><div className="marketing-label">From intake to joining</div><h2>One process. A team that stays aligned.</h2><div className="workflow-steps">{[['01','Define the requirement','Review the client brief, confirm the must-haves and assign the recruiting team.'],['02','Source and screen','Capture candidates, review evidence and record the recruiter’s screening decision.'],['03','Review and submit','Prepare a submission pack, resolve feedback and track the account manager’s approval.'],['04','Interview and place','Coordinate interviews, manage the offer and record the placement and start date.']].map(([number,title,description])=><article key={number}><b>{number}</b><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="marketing-section shell security-section" id="security"><div><div className="marketing-label">Built around your workspace</div><h2>Candidate information deserves careful handling.</h2><p className="section-intro">Keep team access, candidate consent and recruitment decisions part of your process, with workspace boundaries and reviewable history.</p></div><div className="security-list">{[[LockKeyhole,'Workspace isolation','Session-bound access keeps recruiting records within their agency workspace.'],[ShieldCheck,'Role-based workflows','Recruiters, account managers and managers have defined responsibilities and permissions.'],[Check,'People make the hiring decisions','AI-assisted evidence supports recruiter review. Screening and submission approvals stay with your team.']].map(([Icon,title,description])=><div key={title}><Icon size={21}/><div><b>{title}</b><p>{description}</p></div></div>)}</div></section>
    <div className="shell"><section className="marketing-cta"><div><h2>Bring your recruiting team together.</h2><p>Create your agency workspace and configure the way your team recruits.</p></div><Link className="btn primary" href="/signup">Create workspace <ArrowRight size={16}/></Link></section></div>
    <footer className="marketing-footer"><div className="shell"><span>© 2026 XZ Recruiter · XZ TechLabs</span><span>Requirements → Candidates → Submissions → Placements</span></div></footer>
  </main>;
}
